"""
build_email.py
- 读 docs/eess-iv-daily.json
- 渲染成 Gmail 安全的内联 CSS HTML 表格
- 写入指定 HTML 路径（默认 docs/email-body.html）
"""

import argparse
import datetime
import html as html_lib
import json
import os
import sys


def _esc(s):
    if s is None:
        return ""
    return html_lib.escape(str(s), quote=True)


def _summary_cell(p, max_inline=140, en_fallback=240):
    summary_zh = p.get("summary_zh") or ""
    summary_en = p.get("summary_en") or ""

    if summary_zh and summary_zh != summary_en:
        text = _esc(summary_zh).replace("\n", "<br>")
        if len(summary_zh) <= max_inline:
            return f'<span style="color:#222">{text}</span>'
        short = _esc(summary_zh[:max_inline]) + "…"
        return (f'<details style="margin:0">'
                f'<summary style="cursor:pointer;color:#06c">展开中文摘要</summary>'
                f'<div style="margin-top:6px;color:#222;line-height:1.5">{text}</div>'
                f'</details>')

    truncated = summary_en if len(summary_en) <= en_fallback else summary_en[:en_fallback].rsplit(" ", 1)[0] + "…"
    return f'<span style="color:#666">{_esc(truncated)}</span>'


def build_email_html(json_path: str, date_str: str, out_path: str) -> int:
    if not os.path.exists(json_path):
        print(f"[build_email] JSON not found: {json_path}", file=sys.stderr)
        return 0

    with open(json_path, "r", encoding="utf-8") as f:
        content = f.read()
        data = json.loads(content) if content else {}

    all_papers = []
    for topic, papers in data.items():
        if not papers:
            continue
        for _, p in papers.items():
            if isinstance(p, dict):
                all_papers.append(p)
    all_papers.sort(key=lambda x: x.get('update_time', ''), reverse=True)

    date_label = date_str
    try:
        d = datetime.datetime.strptime(date_str, "%Y%m%d")
        date_label = d.strftime("%Y-%m-%d")
    except ValueError:
        pass

    rows_html = []
    for p in all_papers:
        title = _esc(p.get("title", ""))
        url = _esc(p.get("url", ""))
        code_url = _esc(p.get("code_url", ""))
        first_author = _esc(p.get("first_author", ""))
        summary = _summary_cell(p)

        title_html = (f'<a href="{url}" style="color:#1a73e8;text-decoration:none">{title}</a>'
                      if url else title)
        code_html = (f'<a href="{code_url}" style="color:#1a73e8;text-decoration:none">GitHub</a>'
                     if code_url else '<span style="color:#bbb">—</span>')

        rows_html.append(
            f'<tr>'
            f'<td style="padding:8px;border:1px solid #ddd;vertical-align:top;white-space:nowrap">{_esc(p.get("update_time", ""))}</td>'
            f'<td style="padding:8px;border:1px solid #ddd;vertical-align:top">{title_html}</td>'
            f'<td style="padding:8px;border:1px solid #ddd;vertical-align:top;white-space:nowrap">{first_author} et.al.</td>'
            f'<td style="padding:8px;border:1px solid #ddd;vertical-align:top;text-align:center">{code_html}</td>'
            f'<td style="padding:8px;border:1px solid #ddd;vertical-align:top">{summary}</td>'
            f'</tr>'
        )

    table_body = "\n".join(rows_html) if rows_html else (
        '<tr><td colspan="5" style="padding:12px;border:1px solid #ddd;text-align:center;color:#888">'
        '今日无新增 eess.IV 论文</td></tr>'
    )

    html_doc = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<title>eess.IV Daily - {date_label}</title>
</head>
<body style="margin:0;padding:0;background:#f8f8f8;font-family:-apple-system,Helvetica,Arial,sans-serif">
<div style="max-width:980px;margin:0 auto;padding:16px;background:#fff">
  <h2 style="margin:0 0 4px 0;font-size:18px;color:#222">📄 eess.IV Daily · {date_label}</h2>
  <p style="margin:0 0 12px 0;font-size:12px;color:#666">
    来源：arXiv eess.IV (Image and Video Processing) · 过滤医学论文 ·
    仅展示非医学领域每日新增论文
  </p>
  <table style="border-collapse:collapse;width:100%;font-size:13px;border:1px solid #ddd">
    <thead>
      <tr style="background:#f4f4f4">
        <th style="padding:8px;border:1px solid #ddd;text-align:left">Date</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left">Title</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left">Authors</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left">Code</th>
        <th style="padding:8px;border:1px solid #ddd;text-align:left">摘要</th>
      </tr>
    </thead>
    <tbody>
      {table_body}
    </tbody>
  </table>
  <p style="margin:12px 0 0 0;font-size:11px;color:#999">
    Generated by compress-arxiv-daily · GitHub Actions
  </p>
</div>
</body>
</html>
"""

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html_doc)

    print(f"[build_email] wrote {len(all_papers)} papers to {out_path}")
    return len(all_papers)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", default="docs/eess-iv-daily.json")
    parser.add_argument("--date", default=datetime.date.today().strftime("%Y%m%d"))
    parser.add_argument("--out", default="docs/email-body.html")
    args = parser.parse_args()
    build_email_html(args.json, args.date, args.out)
